import type { Metadata } from "next";
import "./globals.css";
import { TabNav } from "@/src/components/layout/TabNav";
import { ShutdownGuard } from "@/src/components/layout/ShutdownGuard";

export const metadata: Metadata = {
  title: "DeutschPath — German Self-Learning",
  description: "AI-powered German learning platform with book reader, vocabulary, grammar, and scenarios",
  icons: { icon: "/favicon.png" },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="de" suppressHydrationWarning>
      <head>
        {/* Anti-flash: set dark class before first paint */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var t = localStorage.getItem('theme');
                  if (t === 'dark' || (!t && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                    document.documentElement.classList.add('dark');
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-screen bg-slate-50 dark:bg-slate-950 transition-colors duration-200">
        <ShutdownGuard />
        <TabNav />
        <main className="pt-[104px] md:pt-16">{children}</main>
        <footer className="mt-12 pb-6 text-center text-xs text-slate-400 dark:text-slate-600 px-4 space-y-1">
          <p>
            Made by{" "}
            <a
              href="https://www.linkedin.com/in/mir-kawashhabibzada/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-slate-500 dark:hover:text-slate-400 transition-colors"
            >
              Mir Kawashhabibzada
            </a>
          </p>
          <p>AI responses are generated by Gemini and may contain mistakes — always verify important German.</p>
        </footer>
      </body>
    </html>
  );
}
